start: false

# 单挑一把个人会输掉/赢得多少分
scores_solo: 20

# 团队竞技输掉/赢得的分
scores_team: 100

# 设置A团队比B团队多几个人时，B团队会每个人加半颗心(1滴血)
# 默认设置为A多一个人B每人多两颗心
# 如果多的玩家少于这个数，玩家的血量将不会有任何变化(不存在百分比加血)
buff_min_players: 1

# 用来单挑的世界
# - world代表的是世界名字，届时会用mv插件传送
# 每个世界要配备两个坐标，分别代表世界中玩家A和玩家B的出生位置
# 写坐标给我写好了啊（写坐标的时候两个逗号中间不要加空格）
# 下方的worlds_for_teamPVP同理
# 再次声明：请严格按照我示例的方式书写世界和坐标！！！
worlds_for_solo:
  - world:
      - 0,0,0
      - 20,0,0
  - world_nether:
      - 0,0,0
      - 20,0,0

worlds_for_team:
  - world:
      - 0,0,0
      - 20,0,0
  - world_nether:
      - 0,0,0
      - 20,0,0

