name: PVPRank
version: '${project.version}'
main: top.mpt.huihui.pvprank.PVPRank
api-version: '1.13'
depend: [Multiverse-Core]

commands:
  pvprank:
    description: PVPRank
  pvp:
    description: Open PVP GUI

permissions:
  pvprank.player:
    description: Allows PVPRank commands
    default: true
  pvprank.operator:
    description: Allows PVPRank OP commands
    default: op
